#--------------------------------------------------------------
# Required inputs
#--------------------------------------------------------------

variable "remote_state_bucket" {
  description = "S3 bucket holding the cluster module's remote state. Used by data.terraform_remote_state.eks per ADR-0001."
  type        = string
  nullable    = false
}

variable "region" {
  description = "AWS region. Also feeds the remote-state key convention <region>/eks/<cluster_name>/terraform.tfstate."
  type        = string
  nullable    = false
}

variable "cluster_name" {
  description = "EKS cluster name. Used as the remote-state key fragment and as aws_eks_addon.cluster_name (read from cluster remote state output at the use site, ADR-0001)."
  type        = string
  nullable    = false
}

#--------------------------------------------------------------
# Addon versions
#--------------------------------------------------------------
#
# Each version variable defaults to null. Null routes to
# data.aws_eks_addon_version.<addon>.version (Phase 7) — the
# AWS-idiomatic "latest compatible" resolution against the
# cluster's K8s version. A non-null literal short-circuits the
# data source and pins the addon exactly, for supply-chain
# control.
#
# The agent's version variable has the additional validation
# that "" is rejected: an empty string is the "tried to pin and
# forgot the value" mistake. Null is permitted (the data source
# resolves) per IMPL-0003 Q3.

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "pod_identity_agent_version" {
  description = "eks-pod-identity-agent addon version. Null resolves via data.aws_eks_addon_version (Phase 7). A non-empty literal pins the version explicitly."
  type        = string
  default     = null

  validation {
    condition     = var.pod_identity_agent_version == null || length(var.pod_identity_agent_version) > 0
    error_message = "pod_identity_agent_version must be null (resolve via data source) or a non-empty version string."
  }
}

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "vpc_cni_version" {
  description = "vpc-cni addon version. Null resolves via data.aws_eks_addon_version (Phase 7)."
  type        = string
  default     = null
}

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "kube_proxy_version" {
  description = "kube-proxy addon version. Null resolves via data.aws_eks_addon_version (Phase 7)."
  type        = string
  default     = null
}

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "coredns_version" {
  description = "coredns addon version. Null resolves via data.aws_eks_addon_version (Phase 7)."
  type        = string
  default     = null
}

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "ebs_csi_version" {
  description = "aws-ebs-csi-driver addon version. Null resolves via data.aws_eks_addon_version (Phase 7)."
  type        = string
  default     = null
}

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "efs_csi_version" {
  description = "aws-efs-csi-driver addon version. Null resolves via data.aws_eks_addon_version (Phase 7). Ignored when efs_csi_enabled is false."
  type        = string
  default     = null
}

#--------------------------------------------------------------
# Addon configuration_values passthroughs
#--------------------------------------------------------------

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "vpc_cni_configuration_values" {
  description = "Free-form JSON string passed through as aws_eks_addon.vpc_cni.configuration_values. Per DESIGN-0003 the schema is owned by AWS; the module only forwards it."
  type        = string
  default     = null
}

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "coredns_configuration_values" {
  description = "Free-form JSON string passed through as aws_eks_addon.coredns.configuration_values."
  type        = string
  default     = null
}

#--------------------------------------------------------------
# EFS CSI opt-in
#--------------------------------------------------------------

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "efs_csi_enabled" {
  description = "Install the aws-efs-csi-driver addon, its IAM role, and its Pod Identity Association. Off by default — most clusters don't need EFS-backed PVs."
  type        = bool
  default     = false
}

#--------------------------------------------------------------
# Tags (typed object; generated by Boilerplate per ADR-0001)
#--------------------------------------------------------------

# tflint-ignore: terraform_unused_declarations  # consumed in a later IMPL-0003 phase
variable "tags" {
  description = "Standard tag set. Generated by Boilerplate from the live-repo Terragrunt config."
  type = object({
    Account     = string
    ClusterName = string
    ClusterType = string
    Environment = string
    Region      = string
  })
}
