#--------------------------------------------------------------
# Local Variables
#--------------------------------------------------------------
#
# Tags arrive pre-formed via var.tags (typed object generated by
# Boilerplate). Per ADR-0001, modules behave as close to pure functions
# as Terraform allows — no internal aggregation of tag fields.

locals {
  # Single reference for cluster encryption + node group EBS encryption.
  # Non-null in both module-managed and external-key modes.
  kms_key_arn = coalesce(
    var.kms_key_arn,
    try(aws_kms_key.cluster[0].arn, null),
  )
}
