#--------------------------------------------------------------
# Local Variables
#--------------------------------------------------------------
#
# Tags arrive pre-formed via var.tags (typed object generated by
# Boilerplate). Per ADR-0001, modules behave as close to pure functions
# as Terraform allows — no internal aggregation of tag fields.
#
# Computed values land here in subsequent phases:
#   local.kms_key_arn  — Phase 3
