#--------------------------------------------------------------
# Shared Variables
#--------------------------------------------------------------

variable "eks_version" {
  description = "EKS control-plane version. Matches the kubelet floor on managed node groups."
  type        = string
  default     = "1.35"
}

variable "name" {
  description = "Cluster Name."
  type        = string
  default     = "libtftest"
}

variable "aws_account_alias_enabled" {
  description = "AWS Account Alias Data Resource enabled."
  type        = bool
  default     = true
}

variable "account_alias" {
  description = "AWS Account Alias if not set."
  type        = string
}

variable "sso_access_enabled" {
  description = "AWS SSO access to cluster via EKS Access Entry enabled."
  type        = bool
  default     = false
}

variable "sso_role_name" {
  description = "AWS SSO Permission Set to Allow"
  type        = string
  default     = "Developer"
}

variable "sso_eks_access_entry" {
  description = "Object mapping for EKS Access Entry"
  type = object({
    kubernetes_groups = list(string)
    user_name         = string
    type              = string
  })
  default = {
    kubernetes_groups = ["dev:readonly"]
    user_name         = "dev:sso-readonly:{{SessionName}}"
    type              = "STANDARD"
  }
}

variable "sso_cluster_policy" {
  description = "Policy to attach to SSO EKS Access Entry"
  type        = string

  validation {
    condition     = contains(["AmazonEKSClusterAdminPolicy", "AmazonEKSAdminPolicy", "AmazonEKSViewPolicy"], var.sso_cluster_policy)
    error_message = "Invalid input, options: \"AmazonEKSClusterAdminPolicy\", \"AmazonEKSAdminPolicy\", \"AmazonEKSViewPolicy\"."
  }
}

variable "sso_cluster_policy_access_scope" {
  description = "Policy to attach to SSO EKS Access scope."
  type        = string
  default     = "cluster"
}

#--------------------------------------------------------------
# Cluster endpoint and logging
#--------------------------------------------------------------

variable "endpoint_private_access" {
  description = "Enable private API server endpoint inside the VPC."
  type        = bool
  default     = true
}

variable "endpoint_public_access" {
  description = "Enable public API server endpoint. Combined with the private endpoint so VPC traffic uses the private path and external operators reach the cluster over the public path."
  type        = bool
  default     = true
}

variable "enabled_cluster_log_types" {
  description = "Control plane log types to ship to CloudWatch. EKS supports: api, audit, authenticator, controllerManager, scheduler."
  type        = list(string)
  default     = ["api", "audit", "authenticator"]
}

variable "cluster_log_retention_in_days" {
  description = "CloudWatch Logs retention for the cluster log group (/aws/eks/<name>/cluster)."
  type        = number
  default     = 30
}

#--------------------------------------------------------------
# KMS envelope encryption
#--------------------------------------------------------------

variable "kms_key_arn" {
  description = "ARN of an externally-managed KMS CMK to use for cluster secret encryption. When null the module creates and manages its own CMK."
  type        = string
  default     = null
}

variable "kms_deletion_window_in_days" {
  description = "Pending-deletion window for the module-managed KMS CMK. Ignored when var.kms_key_arn is set."
  type        = number
  default     = 30

  validation {
    condition     = var.kms_deletion_window_in_days >= 7 && var.kms_deletion_window_in_days <= 30
    error_message = "kms_deletion_window_in_days must be between 7 and 30 (AWS-enforced range)."
  }
}

#--------------------------------------------------------------
# Tags (typed object; generated by Boilerplate per ADR-0001)
#--------------------------------------------------------------

variable "tags" {
  description = "Standard tag set. Generated by Boilerplate from the live-repo Terragrunt config."
  type = object({
    Account     = string
    ClusterName = string
    ClusterType = string
    Environment = string
    Region      = string
  })
}

#--------------------------------------------------------------
# Remote-state composition inputs (per ADR-0001)
#--------------------------------------------------------------

variable "region" {
  description = "AWS region. Also feeds the remote-state key convention <region>/eks/<cluster_name>/terraform.tfstate."
  type        = string
}

variable "remote_state_bucket" {
  description = "S3 bucket holding the VPC stack's remote state, read for VPC ID and subnet IDs."
  type        = string
}

variable "vpc_name" {
  description = "VPC stack name used in the remote-state key for the VPC stack: <region>/vpc/<vpc_name>/terraform.tfstate."
  type        = string
}

#--------------------------------------------------------------
# Data Provider definitions
#--------------------------------------------------------------

# TODO: remove once `var.region` migration lands — region comes from
# Boilerplate-generated Terragrunt. See ADR-0001.
data "aws_region" "this" {}

# Identity-class carve-out under ADR-0001: kept on purpose. Account ID is
# identity (does not drift), the call is free, and hoisting via Boilerplate
# would only relocate the same `sts:GetCallerIdentity` resolution. Used in
# the KMS key resource policy (`arn:aws:iam::<id>:root` principal) and any
# IAM ARN construction in the SSO access entry block.
data "aws_caller_identity" "current" {}

# TODO: remove once `var.account_alias` migration lands — account alias
# comes from Boilerplate-generated Terragrunt. See ADR-0001.
data "aws_iam_account_alias" "this" {
  count = var.aws_account_alias_enabled ? 1 : 0
}

# TODO: replace tag-based VPC discovery with a remote-state read from the
# VPC stack — `data.terraform_remote_state.vpc.outputs.vpc_id` driven by
# `var.remote_state_bucket`, `var.region`, `var.vpc_name`. See ADR-0001:
# live AWS data sources let upstream drift cascade into this module's plan;
# the VPC stack's state file is the contract.
data "aws_vpc" "this" {
  filter {
    name   = "tag:Account"
    values = [local.tags.Account]
  }
}

# TODO: replace with `data.terraform_remote_state.vpc.outputs.private_subnet_ids`.
# See ADR-0001.
data "aws_subnets" "private" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.this.id]
  }
  tags = {
    Network = "Private"
  }
}

# TODO: replace with `data.terraform_remote_state.vpc.outputs.public_subnet_ids`.
# See ADR-0001.
data "aws_subnets" "public" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.this.id]
  }
  tags = {
    Network = "Public"
  }
}
